package com.world.clock.utils

import com.world.clock.data.entity.FavouriteTimeZone
import com.world.clock.model.TimeZoneInfo
import kotlinx.coroutines.delay
import kotlinx.coroutines.flow.Flow
import kotlinx.coroutines.flow.flow
import kotlinx.datetime.TimeZone
import kotlinx.datetime.offsetAt
import kotlinx.datetime.toLocalDateTime
import kotlin.math.abs
import kotlin.time.Clock
import kotlin.time.ExperimentalTime


@OptIn(ExperimentalTime::class)
fun getLocalTimeFormatted(timezone: String, is24Hour: Boolean): String {
    val zone = TimeZone.of(timezone)
    val now = Clock.System.now().toLocalDateTime(zone)

    val hour = if (is24Hour) {
        now.hour
    } else {
        if (now.hour % 12 == 0) 12 else now.hour % 12
    }

    val hourStr = hour.toString().padStart(2, '0')
    val minuteStr = now.minute.toString().padStart(2, '0')
    val secondStr = now.second.toString().padStart(2, '0')

    return if (is24Hour) {
        "$hourStr:$minuteStr:$secondStr"
    } else {
        val amPm = if (now.hour < 12) "AM" else "PM"
        "$hourStr:$minuteStr:$secondStr $amPm"
    }
}


@OptIn(ExperimentalTime::class)
fun getGmtOffsetString(timeZone: TimeZone): String {
    val now = Clock.System.now()
    val offsetSeconds = timeZone.offsetAt(now).totalSeconds

    val hours = offsetSeconds / 3600
    val minutes = (offsetSeconds % 3600) / 60

    val sign = if (hours >= 0) "+" else "-"
    val absHours = abs(hours)
    val absMinutes = abs(minutes)

    return "GMT$sign${absHours.toString().padStart(2, '0')}:${absMinutes.toString().padStart(2, '0')}"
}

fun tickingClock(timezone: String, is24Hour: Boolean): Flow<String> = flow {
    while (true) {
        emit(getLocalTimeFormatted(timezone, is24Hour))
        delay(1000)
    }
}

fun getCurrentTimeZone(): String {
    return TimeZone.currentSystemDefault().id
}


val timeZones = listOf(
    FavouriteTimeZone(id = "Asia/Karachi", name = "Pakistan/Karachi"),
    FavouriteTimeZone(id = "Asia/Karachi", name = "Pakistan/Lahore"),
    FavouriteTimeZone(id = "Asia/Karachi", name = "Pakistan/Islamabad"),
    FavouriteTimeZone(id = "Asia/Karachi", name = "Pakistan/Faisalabad"),
    FavouriteTimeZone(id = "Asia/Karachi", name = "Pakistan/Rawalpindi"),
    FavouriteTimeZone(id = "Asia/Karachi", name = "Pakistan/Multan"),
    FavouriteTimeZone(id = "Asia/Karachi", name = "Pakistan/Gujranwala"),
    FavouriteTimeZone(id = "Asia/Karachi", name = "Pakistan/Peshawar"),
    FavouriteTimeZone(id = "Asia/Karachi", name = "Pakistan/Quetta"),
    FavouriteTimeZone(id = "Asia/Karachi", name = "Pakistan/Hyderabad"),
    FavouriteTimeZone(id = "Asia/Karachi", name = "Pakistan/Sialkot"),

    FavouriteTimeZone(id = "Asia/Kolkata", name = "India/Ahmedabad"),
    FavouriteTimeZone(id = "Asia/Kolkata", name = "India/Bengaluru"),
    FavouriteTimeZone(id = "Asia/Kolkata", name = "India/Bhopal"),
    FavouriteTimeZone(id = "Asia/Kolkata", name = "India/Chandigarh"),
    FavouriteTimeZone(id = "Asia/Kolkata", name = "India/Chennai"),
    FavouriteTimeZone(id = "Asia/Kolkata", name = "India/Delhi"),
    FavouriteTimeZone(id = "Asia/Kolkata", name = "India/Hyderabad"),
    FavouriteTimeZone(id = "Asia/Kolkata", name = "India/Jaipur"),
    FavouriteTimeZone(id = "Asia/Kolkata", name = "India/Kolkata"),
    FavouriteTimeZone(id = "Asia/Kolkata", name = "India/Lucknow"),
    FavouriteTimeZone(id = "Asia/Kolkata", name = "India/Mumbai"),
    FavouriteTimeZone(id = "Asia/Kolkata", name = "India/Nagpur"),
    FavouriteTimeZone(id = "Asia/Kolkata", name = "India/Patna"),
    FavouriteTimeZone(id = "Asia/Kolkata", name = "India/Pune"),
    FavouriteTimeZone(id = "Asia/Kolkata", name = "India/Surat"),

    FavouriteTimeZone(id = "America/New_York", name = "United States/New York"),
    FavouriteTimeZone(id = "America/New_York", name = "United States/Boston"),
    FavouriteTimeZone(id = "America/New_York", name = "United States/Washington DC"),
    FavouriteTimeZone(id = "America/New_York", name = "United States/Philadelphia"),
    FavouriteTimeZone(id = "America/New_York", name = "United States/Atlanta"),
    FavouriteTimeZone(id = "America/New_York", name = "United States/Miami"),
    FavouriteTimeZone(id = "America/New_York", name = "United States/Detroit"),

    FavouriteTimeZone(id = "America/Chicago", name = "United States/Chicago"),
    FavouriteTimeZone(id = "America/Chicago", name = "United States/Houston"),
    FavouriteTimeZone(id = "America/Chicago", name = "United States/Dallas"),
    FavouriteTimeZone(id = "America/Chicago", name = "United States/New Orleans"),
    FavouriteTimeZone(id = "America/Chicago", name = "United States/Minneapolis"),

    FavouriteTimeZone(id = "America/Denver", name = "United States/Denver"),
    FavouriteTimeZone(id = "America/Denver", name = "United States/Salt Lake City"),
    FavouriteTimeZone(id = "America/Denver", name = "United States/Phoenix"),

    FavouriteTimeZone(id = "America/Los_Angeles", name = "United States/Los Angeles"),
    FavouriteTimeZone(id = "America/Los_Angeles", name = "United States/San Francisco"),
    FavouriteTimeZone(id = "America/Los_Angeles", name = "United States/Seattle"),
    FavouriteTimeZone(id = "America/Los_Angeles", name = "United States/San Diego"),
    FavouriteTimeZone(id = "America/Los_Angeles", name = "United States/Portland"),

    FavouriteTimeZone(id = "America/Anchorage", name = "United States/Anchorage"),
    FavouriteTimeZone(id = "America/Anchorage", name = "United States/Juneau"),
    FavouriteTimeZone(id = "America/Adak", name = "United States/Adak"),
    FavouriteTimeZone(id = "Pacific/Honolulu", name = "United States/Honolulu"),

    FavouriteTimeZone(id = "Asia/Shanghai", name = "China/Beijing"),
    FavouriteTimeZone(id = "Asia/Shanghai", name = "China/Shanghai"),
    FavouriteTimeZone(id = "Asia/Shanghai", name = "China/Guangzhou"),
    FavouriteTimeZone(id = "Asia/Shanghai", name = "China/Shenzhen"),
    FavouriteTimeZone(id = "Asia/Shanghai", name = "China/Chengdu"),
    FavouriteTimeZone(id = "Asia/Shanghai", name = "China/Chongqing"),
    FavouriteTimeZone(id = "Asia/Shanghai", name = "China/Hangzhou"),
    FavouriteTimeZone(id = "Asia/Shanghai", name = "China/Tianjin"),
    FavouriteTimeZone(id = "Asia/Shanghai", name = "China/Wuhan"),
    FavouriteTimeZone(id = "Asia/Shanghai", name = "China/Xi'an"),
    FavouriteTimeZone(id = "Asia/Urumqi", name = "China/Ürümqi"),

    FavouriteTimeZone(id = "Europe/Moscow", name = "Russia/Moscow"),
    FavouriteTimeZone(id = "Europe/Moscow", name = "Russia/Saint Petersburg"),
    FavouriteTimeZone(id = "Europe/Kaliningrad", name = "Russia/Kaliningrad"),
    FavouriteTimeZone(id = "Europe/Volgograd", name = "Russia/Volgograd"),
    FavouriteTimeZone(id = "Europe/Samara", name = "Russia/Samara"),
    FavouriteTimeZone(id = "Asia/Yekaterinburg", name = "Russia/Yekaterinburg"),
    FavouriteTimeZone(id = "Asia/Omsk", name = "Russia/Omsk"),
    FavouriteTimeZone(id = "Asia/Krasnoyarsk", name = "Russia/Krasnoyarsk"),
    FavouriteTimeZone(id = "Asia/Irkutsk", name = "Russia/Irkutsk"),
    FavouriteTimeZone(id = "Asia/Yakutsk", name = "Russia/Yakutsk"),
    FavouriteTimeZone(id = "Asia/Vladivostok", name = "Russia/Vladivostok"),
    FavouriteTimeZone(id = "Asia/Magadan", name = "Russia/Magadan"),
    FavouriteTimeZone(id = "Asia/Kamchatka", name = "Russia/Petropavlovsk-Kamchatsky"),

    FavouriteTimeZone(id = "Australia/Sydney", name = "Australia/Sydney"),
    FavouriteTimeZone(id = "Australia/Sydney", name = "Australia/Melbourne"),
    FavouriteTimeZone(id = "Australia/Sydney", name = "Australia/Canberra"),
    FavouriteTimeZone(id = "Australia/Brisbane", name = "Australia/Brisbane"),
    FavouriteTimeZone(id = "Australia/Adelaide", name = "Australia/Adelaide"),
    FavouriteTimeZone(id = "Australia/Perth", name = "Australia/Perth"),
    FavouriteTimeZone(id = "Australia/Darwin", name = "Australia/Darwin"),
    FavouriteTimeZone(id = "Australia/Hobart", name = "Australia/Hobart"),

    FavouriteTimeZone(id = "America/Sao_Paulo", name = "Brazil/São Paulo"),
    FavouriteTimeZone(id = "America/Sao_Paulo", name = "Brazil/Rio de Janeiro"),
    FavouriteTimeZone(id = "America/Sao_Paulo", name = "Brazil/Brasília"),
    FavouriteTimeZone(id = "America/Manaus", name = "Brazil/Manaus"),
    FavouriteTimeZone(id = "America/Recife", name = "Brazil/Recife"),
    FavouriteTimeZone(id = "America/Noronha", name = "Brazil/Fernando de Noronha"),

    FavouriteTimeZone(id = "America/Toronto", name = "Canada/Toronto"),
    FavouriteTimeZone(id = "America/Toronto", name = "Canada/Ottawa"),
    FavouriteTimeZone(id = "America/Montreal", name = "Canada/Montréal"),
    FavouriteTimeZone(id = "America/Vancouver", name = "Canada/Vancouver"),
    FavouriteTimeZone(id = "America/Winnipeg", name = "Canada/Winnipeg"),
    FavouriteTimeZone(id = "America/Edmonton", name = "Canada/Edmonton"),
    FavouriteTimeZone(id = "America/Halifax", name = "Canada/Halifax"),
    FavouriteTimeZone(id = "America/St_Johns", name = "Canada/St. John's"),

    FavouriteTimeZone(id = "Asia/Jakarta", name = "Indonesia/Jakarta"),
    FavouriteTimeZone(id = "Asia/Jakarta", name = "Indonesia/Surabaya"),
    FavouriteTimeZone(id = "Asia/Makassar", name = "Indonesia/Makassar"),
    FavouriteTimeZone(id = "Asia/Jayapura", name = "Indonesia/Jayapura"),

    FavouriteTimeZone(id = "Asia/Dhaka", name = "Bangladesh/Dhaka"),
    FavouriteTimeZone(id = "Asia/Dhaka", name = "Bangladesh/Chittagong"),

    FavouriteTimeZone(id = "Asia/Tokyo", name = "Japan/Tokyo"),
    FavouriteTimeZone(id = "Asia/Tokyo", name = "Japan/Osaka"),
    FavouriteTimeZone(id = "Asia/Tokyo", name = "Japan/Sapporo"),
    FavouriteTimeZone(id = "Asia/Tokyo", name = "Japan/Nagoya"),

    FavouriteTimeZone(id = "Asia/Seoul", name = "South Korea/Seoul"),
    FavouriteTimeZone(id = "Asia/Seoul", name = "South Korea/Busan"),
    FavouriteTimeZone(id = "Asia/Seoul", name = "South Korea/Incheon"),

    FavouriteTimeZone(id = "Europe/London", name = "United Kingdom/London"),
    FavouriteTimeZone(id = "Europe/London", name = "United Kingdom/Manchester"),
    FavouriteTimeZone(id = "Europe/London", name = "United Kingdom/Edinburgh"),
    FavouriteTimeZone(id = "Europe/London", name = "United Kingdom/Birmingham"),

    FavouriteTimeZone(id = "Europe/Berlin", name = "Germany/Berlin"),
    FavouriteTimeZone(id = "Europe/Berlin", name = "Germany/Munich"),
    FavouriteTimeZone(id = "Europe/Berlin", name = "Germany/Frankfurt"),
    FavouriteTimeZone(id = "Europe/Berlin", name = "Germany/Hamburg"),

    FavouriteTimeZone(id = "Europe/Paris", name = "France/Paris"),
    FavouriteTimeZone(id = "Europe/Paris", name = "France/Marseille"),
    FavouriteTimeZone(id = "Europe/Paris", name = "France/Lyon"),

    FavouriteTimeZone(id = "Asia/Riyadh", name = "Saudi Arabia/Riyadh"),
    FavouriteTimeZone(id = "Asia/Riyadh", name = "Saudi Arabia/Jeddah"),
    FavouriteTimeZone(id = "Asia/Riyadh", name = "Saudi Arabia/Mecca"),

    FavouriteTimeZone(id = "Asia/Dubai", name = "United Arab Emirates/Dubai"),
    FavouriteTimeZone(id = "Asia/Dubai", name = "United Arab Emirates/Abu Dhabi"),

    FavouriteTimeZone(id = "Africa/Cairo", name = "Egypt/Cairo"),
    FavouriteTimeZone(id = "Africa/Cairo", name = "Egypt/Alexandria"),

    FavouriteTimeZone(id = "Africa/Johannesburg", name = "South Africa/Johannesburg"),
    FavouriteTimeZone(id = "Africa/Johannesburg", name = "South Africa/Cape Town"),
    FavouriteTimeZone(id = "Africa/Johannesburg", name = "South Africa/Durban"),

    FavouriteTimeZone(id = "Africa/Lagos", name = "Nigeria/Lagos"),
    FavouriteTimeZone(id = "Africa/Lagos", name = "Nigeria/Abuja"),

    FavouriteTimeZone(id = "Africa/Nairobi", name = "Kenya/Nairobi"),
    FavouriteTimeZone(id = "Africa/Nairobi", name = "Kenya/Mombasa"),

    FavouriteTimeZone(id = "Asia/Singapore", name = "Singapore"),

    FavouriteTimeZone(id = "Asia/Kuala_Lumpur", name = "Malaysia/Kuala Lumpur"),
    FavouriteTimeZone(id = "Asia/Kuala_Lumpur", name = "Malaysia/George Town"),

    FavouriteTimeZone(id = "Asia/Bangkok", name = "Thailand/Bangkok"),
    FavouriteTimeZone(id = "Asia/Bangkok", name = "Thailand/Chiang Mai"),

    FavouriteTimeZone(id = "Asia/Ho_Chi_Minh", name = "Vietnam/Ho Chi Minh City"),
    FavouriteTimeZone(id = "Asia/Ho_Chi_Minh", name = "Vietnam/Hanoi"),

    FavouriteTimeZone(id = "Asia/Manila", name = "Philippines/Manila"),
    FavouriteTimeZone(id = "Asia/Manila", name = "Philippines/Davao"),
    FavouriteTimeZone(id = "Asia/Manila", name = "Philippines/Cebu"),

    FavouriteTimeZone(id = "America/Argentina/Buenos_Aires", name = "Argentina/Buenos Aires"),
    FavouriteTimeZone(id = "America/Argentina/Buenos_Aires", name = "Argentina/Córdoba"),
    FavouriteTimeZone(id = "America/Argentina/Buenos_Aires", name = "Argentina/Rosario"),

    FavouriteTimeZone(id = "America/Mexico_City", name = "Mexico/Mexico City"),
    FavouriteTimeZone(id = "America/Mexico_City", name = "Mexico/Guadalajara"),
    FavouriteTimeZone(id = "America/Tijuana", name = "Mexico/Tijuana"),
    FavouriteTimeZone(id = "America/Cancun", name = "Mexico/Cancún"),

    FavouriteTimeZone(id = "Europe/Istanbul", name = "Turkey/Istanbul"),
    FavouriteTimeZone(id = "Europe/Istanbul", name = "Turkey/Ankara"),
    FavouriteTimeZone(id = "Europe/Istanbul", name = "Turkey/Izmir"),

    FavouriteTimeZone(id = "Europe/Kyiv", name = "Ukraine/Kyiv"),
    FavouriteTimeZone(id = "Europe/Kyiv", name = "Ukraine/Kharkiv"),
    FavouriteTimeZone(id = "Europe/Kyiv", name = "Ukraine/Odesa"),

    FavouriteTimeZone(id = "Europe/Rome", name = "Italy/Rome"),
    FavouriteTimeZone(id = "Europe/Rome", name = "Italy/Milan"),
    FavouriteTimeZone(id = "Europe/Rome", name = "Italy/Naples"),

    FavouriteTimeZone(id = "Europe/Madrid", name = "Spain/Madrid"),
    FavouriteTimeZone(id = "Europe/Madrid", name = "Spain/Barcelona"),
    FavouriteTimeZone(id = "Europe/Madrid", name = "Spain/Valencia"),
    FavouriteTimeZone(id = "Atlantic/Canary", name = "Spain/Tenerife"),

    FavouriteTimeZone(id = "Europe/Amsterdam", name = "Netherlands/Amsterdam"),
    FavouriteTimeZone(id = "Europe/Amsterdam", name = "Netherlands/Rotterdam"),

    FavouriteTimeZone(id = "Europe/Zurich", name = "Switzerland/Zurich"),
    FavouriteTimeZone(id = "Europe/Zurich", name = "Switzerland/Geneva"),

    FavouriteTimeZone(id = "Europe/Stockholm", name = "Sweden/Stockholm"),
    FavouriteTimeZone(id = "Europe/Stockholm", name = "Sweden/Gothenburg"),

    FavouriteTimeZone(id = "Europe/Oslo", name = "Norway/Oslo"),
    FavouriteTimeZone(id = "Europe/Oslo", name = "Norway/Bergen"),

    FavouriteTimeZone(id = "Pacific/Auckland", name = "New Zealand/Auckland"),
    FavouriteTimeZone(id = "Pacific/Auckland", name = "New Zealand/Wellington"),
    FavouriteTimeZone(id = "Pacific/Chatham", name = "New Zealand/Chatham Islands"),

    FavouriteTimeZone(id = "Asia/Kabul", name = "Afghanistan/Kabul"),
    FavouriteTimeZone(id = "Europe/Tirane", name = "Albania/Tirane"),
    FavouriteTimeZone(id = "Africa/Algiers", name = "Algeria/Algiers"),
    FavouriteTimeZone(id = "Europe/Andorra", name = "Andorra/Andorra la Vella"),
    FavouriteTimeZone(id = "Africa/Luanda", name = "Angola/Luanda"),
    FavouriteTimeZone(id = "Asia/Yerevan", name = "Armenia/Yerevan"),
    FavouriteTimeZone(id = "Europe/Vienna", name = "Austria/Vienna"),
    FavouriteTimeZone(id = "Asia/Baku", name = "Azerbaijan/Baku"),
    FavouriteTimeZone(id = "America/Nassau", name = "Bahamas/Nassau"),
    FavouriteTimeZone(id = "Asia/Bahrain", name = "Bahrain/Manama"),
    FavouriteTimeZone(id = "Europe/Minsk", name = "Belarus/Minsk"),
    FavouriteTimeZone(id = "Europe/Brussels", name = "Belgium/Brussels"),
    FavouriteTimeZone(id = "America/La_Paz", name = "Bolivia/La Paz"),
    FavouriteTimeZone(id = "Europe/Sarajevo", name = "Bosnia & Herzegovina/Sarajevo"),
    FavouriteTimeZone(id = "Africa/Gaborone", name = "Botswana/Gaborone"),
    FavouriteTimeZone(id = "Asia/Brunei", name = "Brunei/Bandar Seri Begawan"),
    FavouriteTimeZone(id = "Europe/Sofia", name = "Bulgaria/Sofia"),
    FavouriteTimeZone(id = "Asia/Phnom_Penh", name = "Cambodia/Phnom Penh"),
    FavouriteTimeZone(id = "Africa/Douala", name = "Cameroon/Douala"),
    FavouriteTimeZone(id = "America/Santiago", name = "Chile/Santiago"),
    FavouriteTimeZone(id = "Pacific/Easter", name = "Chile/Easter Island"),
    FavouriteTimeZone(id = "America/Bogota", name = "Colombia/Bogotá"),
    FavouriteTimeZone(id = "America/Costa_Rica", name = "Costa Rica/San José"),
    FavouriteTimeZone(id = "Europe/Zagreb", name = "Croatia/Zagreb"),
    FavouriteTimeZone(id = "America/Havana", name = "Cuba/Havana"),
    FavouriteTimeZone(id = "Asia/Nicosia", name = "Cyprus/Nicosia"),
    FavouriteTimeZone(id = "Asia/Famagusta", name = "Cyprus/North Nicosia"),
    FavouriteTimeZone(id = "Europe/Prague", name = "Czechia/Prague"),
    FavouriteTimeZone(id = "Europe/Copenhagen", name = "Denmark/Copenhagen"),
    FavouriteTimeZone(id = "America/Santo_Domingo", name = "Dominican Republic/Santo Domingo"),
    FavouriteTimeZone(id = "America/Guayaquil", name = "Ecuador/Quito"),
    FavouriteTimeZone(id = "Pacific/Galapagos", name = "Ecuador/Galapagos"),
    FavouriteTimeZone(id = "America/El_Salvador", name = "El Salvador/San Salvador"),
    FavouriteTimeZone(id = "Europe/Tallinn", name = "Estonia/Tallinn"),
    FavouriteTimeZone(id = "Africa/Addis_Ababa", name = "Ethiopia/Addis Ababa"),
    FavouriteTimeZone(id = "Pacific/Fiji", name = "Fiji/Suva"),
    FavouriteTimeZone(id = "Europe/Helsinki", name = "Finland/Helsinki"),
    FavouriteTimeZone(id = "Asia/Tbilisi", name = "Georgia/Tbilisi"),
    FavouriteTimeZone(id = "Africa/Accra", name = "Ghana/Accra"),
    FavouriteTimeZone(id = "Europe/Athens", name = "Greece/Athens"),
    FavouriteTimeZone(id = "America/Guatemala", name = "Guatemala/Guatemala City"),
    FavouriteTimeZone(id = "America/Tegucigalpa", name = "Honduras/Tegucigalpa"),
    FavouriteTimeZone(id = "Europe/Budapest", name = "Hungary/Budapest"),
    FavouriteTimeZone(id = "Atlantic/Reykjavik", name = "Iceland/Reykjavík"),
    FavouriteTimeZone(id = "Asia/Tehran", name = "Iran/Tehran"),
    FavouriteTimeZone(id = "Asia/Baghdad", name = "Iraq/Baghdad"),
    FavouriteTimeZone(id = "Europe/Dublin", name = "Ireland/Dublin"),
    FavouriteTimeZone(id = "Asia/Jerusalem", name = "Israel/Jerusalem"),
    FavouriteTimeZone(id = "Asia/Gaza", name = "Palestine/Gaza"),
    FavouriteTimeZone(id = "Asia/Hebron", name = "Palestine/Hebron"),
    FavouriteTimeZone(id = "Africa/Abidjan", name = "Ivory Coast/Abidjan"),
    FavouriteTimeZone(id = "America/Jamaica", name = "Jamaica/Kingston"),
    FavouriteTimeZone(id = "Asia/Amman", name = "Jordan/Amman"),
    FavouriteTimeZone(id = "Asia/Almaty", name = "Kazakhstan/Almaty"),
    FavouriteTimeZone(id = "Asia/Qostanay", name = "Kazakhstan/Astana"),
    FavouriteTimeZone(id = "Asia/Kuwait", name = "Kuwait/Kuwait City"),
    FavouriteTimeZone(id = "Europe/Riga", name = "Latvia/Riga"),
    FavouriteTimeZone(id = "Asia/Beirut", name = "Lebanon/Beirut"),
    FavouriteTimeZone(id = "Africa/Tripoli", name = "Libya/Tripoli"),
    FavouriteTimeZone(id = "Europe/Vaduz", name = "Liechtenstein/Vaduz"),
    FavouriteTimeZone(id = "Europe/Vilnius", name = "Lithuania/Vilnius"),
    FavouriteTimeZone(id = "Europe/Luxembourg", name = "Luxembourg"),
    FavouriteTimeZone(id = "Europe/Skopje", name = "North Macedonia/Skopje"),
    FavouriteTimeZone(id = "Indian/Antananarivo", name = "Madagascar/Antananarivo"),
    FavouriteTimeZone(id = "Indian/Maldives", name = "Maldives/Malé"),
    FavouriteTimeZone(id = "Europe/Malta", name = "Malta/Valletta"),
    FavouriteTimeZone(id = "Indian/Mauritius", name = "Mauritius/Port Louis"),
    FavouriteTimeZone(id = "Europe/Chisinau", name = "Moldova/Chișinău"),
    FavouriteTimeZone(id = "Europe/Monaco", name = "Monaco"),
    FavouriteTimeZone(id = "Asia/Ulaanbaatar", name = "Mongolia/Ulaanbaatar"),
    FavouriteTimeZone(id = "Europe/Podgorica", name = "Montenegro/Podgorica"),
    FavouriteTimeZone(id = "Africa/Casablanca", name = "Morocco/Casablanca"),
    FavouriteTimeZone(id = "Asia/Yangon", name = "Myanmar/Yangon"),
    FavouriteTimeZone(id = "Asia/Kathmandu", name = "Nepal/Kathmandu"),
    FavouriteTimeZone(id = "Asia/Pyongyang", name = "North Korea/Pyongyang"),
    FavouriteTimeZone(id = "Asia/Muscat", name = "Oman/Muscat"),
    FavouriteTimeZone(id = "America/Panama", name = "Panama/Panama City"),
    FavouriteTimeZone(id = "America/Asuncion", name = "Paraguay/Asunción"),
    FavouriteTimeZone(id = "America/Lima", name = "Peru/Lima"),
    FavouriteTimeZone(id = "Europe/Warsaw", name = "Poland/Warsaw"),
    FavouriteTimeZone(id = "Europe/Lisbon", name = "Portugal/Lisbon"),
    FavouriteTimeZone(id = "Atlantic/Azores", name = "Portugal/Ponta Delgada"),
    FavouriteTimeZone(id = "Atlantic/Madeira", name = "Portugal/Funchal"),
    FavouriteTimeZone(id = "Asia/Qatar", name = "Qatar/Doha"),
    FavouriteTimeZone(id = "Europe/Bucharest", name = "Romania/Bucharest"),
    FavouriteTimeZone(id = "Africa/Kigali", name = "Rwanda/Kigali"),
    FavouriteTimeZone(id = "Africa/Dakar", name = "Senegal/Dakar"),
    FavouriteTimeZone(id = "Europe/Belgrade", name = "Serbia/Belgrade"),
    FavouriteTimeZone(id = "Indian/Mahe", name = "Seychelles/Victoria"),
    FavouriteTimeZone(id = "Africa/Freetown", name = "Sierra Leone/Freetown"),
    FavouriteTimeZone(id = "Europe/Bratislava", name = "Slovakia/Bratislava"),
    FavouriteTimeZone(id = "Europe/Ljubljana", name = "Slovenia/Ljubljana"),
    FavouriteTimeZone(id = "Africa/Mogadishu", name = "Somalia/Mogadishu"),
    FavouriteTimeZone(id = "Asia/Colombo", name = "Sri Lanka/Colombo"),
    FavouriteTimeZone(id = "Africa/Khartoum", name = "Sudan/Khartoum"),
    FavouriteTimeZone(id = "Asia/Damascus", name = "Syria/Damascus"),
    FavouriteTimeZone(id = "Asia/Taipei", name = "Taiwan/Taipei"),
    FavouriteTimeZone(id = "Asia/Dushanbe", name = "Tajikistan/Dushanbe"),
    FavouriteTimeZone(id = "Africa/Dar_es_Salaam", name = "Tanzania/Dar es Salaam"),
    FavouriteTimeZone(id = "Asia/Dili", name = "Timor-Leste/Dili"),
    FavouriteTimeZone(id = "Africa/Tunis", name = "Tunisia/Tunis"),
    FavouriteTimeZone(id = "Asia/Ashgabat", name = "Turkmenistan/Ashgabat"),
    FavouriteTimeZone(id = "Africa/Kampala", name = "Uganda/Kampala"),
    FavouriteTimeZone(id = "America/Montevideo", name = "Uruguay/Montevideo"),
    FavouriteTimeZone(id = "Asia/Tashkent", name = "Uzbekistan/Tashkent"),
    FavouriteTimeZone(id = "Asia/Samarkand", name = "Uzbekistan/Samarkand"),
    FavouriteTimeZone(id = "Europe/Vatican", name = "Vatican City"),
    FavouriteTimeZone(id = "America/Caracas", name = "Venezuela/Caracas"),
    FavouriteTimeZone(id = "Asia/Aden", name = "Yemen/Sana'a"),
    FavouriteTimeZone(id = "Africa/Lusaka", name = "Zambia/Lusaka"),
    FavouriteTimeZone(id = "Africa/Harare", name = "Zimbabwe/Harare"),

    FavouriteTimeZone(id = "UTC", name = "UTC/Coordinated Universal Time"),
    FavouriteTimeZone(id = "UTC", name = "UTC/GMT")
    // Africa
//    "Africa/Abidjan",
//    "Africa/Accra",
//    "Africa/Addis_Ababa",
//    "Africa/Algiers",
//    "Africa/Asmara",
//    "Africa/Bamako",
//    "Africa/Bangui",
//    "Africa/Banjul",
//    "Africa/Bissau",
//    "Africa/Blantyre",
//    "Africa/Brazzaville",
//    "Africa/Bujumbura",
//    "Africa/Cairo",
//    "Africa/Casablanca",
//    "Africa/Ceuta",
//    "Africa/Conakry",
//    "Africa/Dakar",
//    "Africa/Dar_es_Salaam",
//    "Africa/Djibouti",
//    "Africa/Douala",
//    "Africa/El_Aaiun",
//    "Africa/Freetown",
//    "Africa/Gaborone",
//    "Africa/Harare",
//    "Africa/Johannesburg",
//    "Africa/Juba",
//    "Africa/Kampala",
//    "Africa/Khartoum",
//    "Africa/Kigali",
//    "Africa/Kinshasa",
//    "Africa/Lagos",
//    "Africa/Libreville",
//    "Africa/Lome",
//    "Africa/Luanda",
//    "Africa/Lubumbashi",
//    "Africa/Lusaka",
//    "Africa/Malabo",
//    "Africa/Maputo",
//    "Africa/Maseru",
//    "Africa/Mbabane",
//    "Africa/Mogadishu",
//    "Africa/Monrovia",
//    "Africa/Nairobi",
//    "Africa/Ndjamena",
//    "Africa/Niamey",
//    "Africa/Nouakchott",
//    "Africa/Ouagadougou",
//    "Africa/Porto-Novo",
//    "Africa/Sao_Tome",
//    "Africa/Tripoli",
//    "Africa/Tunis",
//    "Africa/Windhoek",
//
//    // America
//    "America/Adak",
//    "America/Anchorage",
//    "America/Anguilla",
//    "America/Antigua",
//    "America/Araguaina",
//    "America/Argentina/Buenos_Aires",
//    "America/Argentina/Catamarca",
//    "America/Argentina/Cordoba",
//    "America/Argentina/Jujuy",
//    "America/Argentina/La_Rioja",
//    "America/Argentina/Mendoza",
//    "America/Argentina/Rio_Gallegos",
//    "America/Argentina/Salta",
//    "America/Argentina/San_Juan",
//    "America/Argentina/San_Luis",
//    "America/Argentina/Tucuman",
//    "America/Argentina/Ushuaia",
//    "America/Aruba",
//    "America/Asuncion",
//    "America/Atikokan",
//    "America/Bahia",
//    "America/Bahia_Banderas",
//    "America/Barbados",
//    "America/Belem",
//    "America/Belize",
//    "America/Blanc-Sablon",
//    "America/Boa_Vista",
//    "America/Bogota",
//    "America/Boise",
//    "America/Cambridge_Bay",
//    "America/Campo_Grande",
//    "America/Cancun",
//    "America/Caracas",
//    "America/Cayenne",
//    "America/Cayman",
//    "America/Chicago",
//    "America/Chihuahua",
//    "America/Ciudad_Juarez",
//    "America/Costa_Rica",
//    "America/Creston",
//    "America/Cuiaba",
//    "America/Curacao",
//    "America/Danmarkshavn",
//    "America/Dawson",
//    "America/Dawson_Creek",
//    "America/Denver",
//    "America/Detroit",
//    "America/Dominica",
//    "America/Edmonton",
//    "America/Eirunepe",
//    "America/El_Salvador",
//    "America/Fort_Nelson",
//    "America/Fortaleza",
//    "America/Glace_Bay",
//    "America/Goose_Bay",
//    "America/Grand_Turk",
//    "America/Grenada",
//    "America/Guadeloupe",
//    "America/Guatemala",
//    "America/Guayaquil",
//    "America/Guyana",
//    "America/Halifax",
//    "America/Havana",
//    "America/Hermosillo",
//    "America/Indiana/Indianapolis",
//    "America/Indiana/Knox",
//    "America/Indiana/Marengo",
//    "America/Indiana/Petersburg",
//    "America/Indiana/Tell_City",
//    "America/Indiana/Vevay",
//    "America/Indiana/Vincennes",
//    "America/Indiana/Winamac",
//    "America/Inuvik",
//    "America/Iqaluit",
//    "America/Jamaica",
//    "America/Juneau",
//    "America/Kentucky/Louisville",
//    "America/Kentucky/Monticello",
//    "America/Kralendijk",
//    "America/La_Paz",
//    "America/Lima",
//    "America/Los_Angeles",
//    "America/Lower_Princes",
//    "America/Maceio",
//    "America/Managua",
//    "America/Manaus",
//    "America/Marigot",
//    "America/Martinique",
//    "America/Matamoros",
//    "America/Mazatlan",
//    "America/Menominee",
//    "America/Merida",
//    "America/Metlakatla",
//    "America/Mexico_City",
//    "America/Miquelon",
//    "America/Moncton",
//    "America/Monterrey",
//    "America/Montevideo",
//    "America/Montserrat",
//    "America/Nassau",
//    "America/New_York",
//    "America/Nome",
//    "America/Noronha",
//    "America/North_Dakota/Beulah",
//    "America/North_Dakota/Center",
//    "America/North_Dakota/New_Salem",
//    "America/Nuuk",
//    "America/Ojinaga",
//    "America/Panama",
//    "America/Paramaribo",
//    "America/Phoenix",
//    "America/Port-au-Prince",
//    "America/Port_of_Spain",
//    "America/Porto_Velho",
//    "America/Puerto_Rico",
//    "America/Punta_Arenas",
//    "America/Rankin_Inlet",
//    "America/Recife",
//    "America/Regina",
//    "America/Resolute",
//    "America/Rio_Branco",
//    "America/Santarem",
//    "America/Santiago",
//    "America/Santo_Domingo",
//    "America/Sao_Paulo",
//    "America/Scoresbysund",
//    "America/Sitka",
//    "America/St_Barthelemy",
//    "America/St_Johns",
//    "America/St_Kitts",
//    "America/St_Lucia",
//    "America/St_Thomas",
//    "America/St_Vincent",
//    "America/Swift_Current",
//    "America/Tegucigalpa",
//    "America/Thule",
//    "America/Tijuana",
//    "America/Toronto",
//    "America/Tortola",
//    "America/Vancouver",
//    "America/Whitehorse",
//    "America/Winnipeg",
//    "America/Yakutat",
//
//    // Antarctica
//    "Antarctica/Casey",
//    "Antarctica/Davis",
//    "Antarctica/DumontDUrville",
//    "Antarctica/Macquarie",
//    "Antarctica/Mawson",
//    "Antarctica/McMurdo",
//    "Antarctica/Palmer",
//    "Antarctica/Rothera",
//    "Antarctica/Syowa",
//    "Antarctica/Troll",
//    "Antarctica/Vostok",
//
//    // Arctic
//    "Arctic/Longyearbyen",
//
//    // Asia
//    "Asia/Aden",
//    "Asia/Almaty",
//    "Asia/Amman",
//    "Asia/Anadyr",
//    "Asia/Aqtau",
//    "Asia/Aqtobe",
//    "Asia/Ashgabat",
//    "Asia/Atyrau",
//    "Asia/Baghdad",
//    "Asia/Bahrain",
//    "Asia/Baku",
//    "Asia/Bangkok",
//    "Asia/Barnaul",
//    "Asia/Beirut",
//    "Asia/Bishkek",
//    "Asia/Brunei",
//    "Asia/Chita",
//    "Asia/Choibalsan",
//    "Asia/Colombo",
//    "Asia/Damascus",
//    "Asia/Dhaka",
//    "Asia/Dili",
//    "Asia/Dubai",
//    "Asia/Dushanbe",
//    "Asia/Famagusta",
//    "Asia/Gaza",
//    "Asia/Hebron",
//    "Asia/Ho_Chi_Minh",
//    "Asia/Hong_Kong",
//    "Asia/Hovd",
//    "Asia/Irkutsk",
//    "Asia/Jakarta",
//    "Asia/Jayapura",
//    "Asia/Jerusalem",
//    "Asia/Kabul",
//    "Asia/Kamchatka",
//    "Asia/Karachi",
//    "Asia/Kathmandu",
//    "Asia/Khandyga",
//    "Asia/Kolkata",
//    "Asia/Krasnoyarsk",
//    "Asia/Kuala_Lumpur",
//    "Asia/Kuching",
//    "Asia/Kuwait",
//    "Asia/Macau",
//    "Asia/Magadan",
//    "Asia/Makassar",
//    "Asia/Manila",
//    "Asia/Muscat",
//    "Asia/Nicosia",
//    "Asia/Novokuznetsk",
//    "Asia/Novosibirsk",
//    "Asia/Omsk",
//    "Asia/Oral",
//    "Asia/Phnom_Penh",
//    "Asia/Pontianak",
//    "Asia/Pyongyang",
//    "Asia/Qatar",
//    "Asia/Qostanay",
//    "Asia/Qyzylorda",
//    "Asia/Riyadh",
//    "Asia/Sakhalin",
//    "Asia/Samarkand",
//    "Asia/Seoul",
//    "Asia/Shanghai",
//    "Asia/Singapore",
//    "Asia/Srednekolymsk",
//    "Asia/Taipei",
//    "Asia/Tashkent",
//    "Asia/Tbilisi",
//    "Asia/Tehran",
//    "Asia/Thimphu",
//    "Asia/Tokyo",
//    "Asia/Tomsk",
//    "Asia/Ulaanbaatar",
//    "Asia/Urumqi",
//    "Asia/Ust-Nera",
//    "Asia/Vientiane",
//    "Asia/Vladivostok",
//    "Asia/Yakutsk",
//    "Asia/Yangon",
//    "Asia/Yekaterinburg",
//    "Asia/Yerevan",
//
//    // Atlantic
//    "Atlantic/Azores",
//    "Atlantic/Bermuda",
//    "Atlantic/Canary",
//    "Atlantic/Cape_Verde",
//    "Atlantic/Faroe",
//    "Atlantic/Madeira",
//    "Atlantic/Reykjavik",
//    "Atlantic/South_Georgia",
//    "Atlantic/St_Helena",
//    "Atlantic/Stanley",
//
//    // Australia
//    "Australia/Adelaide",
//    "Australia/Brisbane",
//    "Australia/Broken_Hill",
//    "Australia/Darwin",
//    "Australia/Eucla",
//    "Australia/Hobart",
//    "Australia/Lindeman",
//    "Australia/Lord_Howe",
//    "Australia/Melbourne",
//    "Australia/Perth",
//    "Australia/Sydney",
//
//    // Europe
//    "Europe/Amsterdam",
//    "Europe/Andorra",
//    "Europe/Astrakhan",
//    "Europe/Athens",
//    "Europe/Belgrade",
//    "Europe/Berlin",
//    "Europe/Bratislava",
//    "Europe/Brussels",
//    "Europe/Bucharest",
//    "Europe/Budapest",
//    "Europe/Busingen",
//    "Europe/Chisinau",
//    "Europe/Copenhagen",
//    "Europe/Dublin",
//    "Europe/Gibraltar",
//    "Europe/Guernsey",
//    "Europe/Helsinki",
//    "Europe/Isle_of_Man",
//    "Europe/Istanbul",
//    "Europe/Jersey",
//    "Europe/Kaliningrad",
//    "Europe/Kirov",
//    "Europe/Kyiv",
//    "Europe/Lisbon",
//    "Europe/Ljubljana",
//    "Europe/London",
//    "Europe/Luxembourg",
//    "Europe/Madrid",
//    "Europe/Malta",
//    "Europe/Mariehamn",
//    "Europe/Minsk",
//    "Europe/Monaco",
//    "Europe/Moscow",
//    "Europe/Oslo",
//    "Europe/Paris",
//    "Europe/Podgorica",
//    "Europe/Prague",
//    "Europe/Riga",
//    "Europe/Rome",
//    "Europe/Samara",
//    "Europe/San_Marino",
//    "Europe/Sarajevo",
//    "Europe/Saratov",
//    "Europe/Simferopol",
//    "Europe/Skopje",
//    "Europe/Sofia",
//    "Europe/Stockholm",
//    "Europe/Tallinn",
//    "Europe/Tirane",
//    "Europe/Ulyanovsk",
//    "Europe/Vaduz",
//    "Europe/Vatican",
//    "Europe/Vienna",
//    "Europe/Vilnius",
//    "Europe/Volgograd",
//    "Europe/Warsaw",
//    "Europe/Zagreb",
//    "Europe/Zurich",
//
//    // Indian
//    "Indian/Antananarivo",
//    "Indian/Chagos",
//    "Indian/Christmas",
//    "Indian/Cocos",
//    "Indian/Comoro",
//    "Indian/Kerguelen",
//    "Indian/Mahe",
//    "Indian/Maldives",
//    "Indian/Mauritius",
//    "Indian/Mayotte",
//    "Indian/Reunion",
//
//    // Pacific
//    "Pacific/Apia",
//    "Pacific/Auckland",
//    "Pacific/Bougainville",
//    "Pacific/Chatham",
//    "Pacific/Chuuk",
//    "Pacific/Easter",
//    "Pacific/Efate",
//    "Pacific/Fakaofo",
//    "Pacific/Fiji",
//    "Pacific/Funafuti",
//    "Pacific/Galapagos",
//    "Pacific/Gambier",
//    "Pacific/Guadalcanal",
//    "Pacific/Guam",
//    "Pacific/Honolulu",
//    "Pacific/Kanton",
//    "Pacific/Kiritimati",
//    "Pacific/Kosrae",
//    "Pacific/Kwajalein",
//    "Pacific/Majuro",
//    "Pacific/Marquesas",
//    "Pacific/Midway",
//    "Pacific/Nauru",
//    "Pacific/Niue",
//    "Pacific/Norfolk",
//    "Pacific/Noumea",
//    "Pacific/Pago_Pago",
//    "Pacific/Palau",
//    "Pacific/Pitcairn",
//    "Pacific/Pohnpei",
//    "Pacific/Port_Moresby",
//    "Pacific/Rarotonga",
//    "Pacific/Saipan",
//    "Pacific/Tahiti",
//    "Pacific/Tarawa",
//    "Pacific/Tongatapu",
//    "Pacific/Wake",
//    "Pacific/Wallis",
//
//    // UTC
//    "UTC"
)


