package com.world.clock.utils

import com.world.clock.data.entity.FavouriteTimeZone
import com.world.clock.model.TimeZoneInfo
import kotlinx.coroutines.delay
import kotlinx.coroutines.flow.Flow
import kotlinx.coroutines.flow.flow
import kotlinx.datetime.LocalDateTime
import kotlinx.datetime.TimeZone
import kotlinx.datetime.atTime
import kotlinx.datetime.number
import kotlinx.datetime.offsetAt
import kotlinx.datetime.toInstant
import kotlinx.datetime.toLocalDateTime
import kotlinx.datetime.todayIn
import kotlin.math.abs
import kotlin.time.Clock
import kotlin.time.ExperimentalTime


@OptIn(ExperimentalTime::class)
fun getLocalTimeFormatted(timezone: String, is24Hour: Boolean): String {
    val zone = TimeZone.of(timezone)
    val now = Clock.System.now().toLocalDateTime(zone)

    val hour = if (is24Hour) {
        now.hour
    } else {
        if (now.hour % 12 == 0) 12 else now.hour % 12
    }

    val hourStr = hour.toString().padStart(2, '0')
    val minuteStr = now.minute.toString().padStart(2, '0')
    val secondStr = now.second.toString().padStart(2, '0')

    return if (is24Hour) {
        "$hourStr:$minuteStr:$secondStr"
    } else {
        val amPm = if (now.hour < 12) "AM" else "PM"
        "$hourStr:$minuteStr:$secondStr $amPm"
    }
}

@OptIn(ExperimentalTime::class)
fun getLocalDateFormatted(timezone: String): String {
    val zone = TimeZone.of(timezone)
    val now = Clock.System.now().toLocalDateTime(zone)

    val year = now.year
    val month = now.month.number.toString().padStart(2, '0')
    val day = now.day.toString().padStart(2, '0')

    return "$year-$month-$day" // format: YYYY-MM-DD
}

@OptIn(ExperimentalTime::class)
fun getLocalTimeFromUtc(timezone: String, utcHour: Int, utcMinute: Int, is24Hour: Boolean): String {
    val utcDateTime = LocalDateTime(2025, 1, 1, utcHour, utcMinute)
    val utcInstant = utcDateTime.toInstant(TimeZone.UTC)
    val local = utcInstant.toLocalDateTime(TimeZone.of(timezone))

    val hour = if (is24Hour) local.hour else if (local.hour % 12 == 0) 12 else local.hour % 12
    val hourStr = hour.toString().padStart(2, '0')
    val minuteStr = local.minute.toString().padStart(2, '0')
    val amPm = if (is24Hour) "" else if (local.hour < 12) " AM" else " PM"

    return "$hourStr:$minuteStr$amPm"
}

@OptIn(ExperimentalTime::class)
fun getLocalDateFromUtc(timezone: String, utcHour: Int, utcMinute: Int): String {
    val utcDateTime = LocalDateTime(2025, 1, 1, utcHour, utcMinute)
    val utcInstant = utcDateTime.toInstant(TimeZone.UTC)
    val local = utcInstant.toLocalDateTime(TimeZone.of(timezone))
    return "${local.date.day}-${local.date.month.number}-${local.date.year}"
}




@OptIn(ExperimentalTime::class)
fun getGmtOffsetString(timeZone: TimeZone): String {
    val now = Clock.System.now()
    val offsetSeconds = timeZone.offsetAt(now).totalSeconds

    val hours = offsetSeconds / 3600
    val minutes = (offsetSeconds % 3600) / 60

    val sign = if (hours >= 0) "+" else "-"
    val absHours = abs(hours)
    val absMinutes = abs(minutes)

    return "GMT$sign${absHours.toString().padStart(2, '0')}:${absMinutes.toString().padStart(2, '0')}"
}

fun tickingClock(timezone: String, is24Hour: Boolean): Flow<String> = flow {
    while (true) {
        emit(getLocalTimeFormatted(timezone, is24Hour))
        delay(1000)
    }
}

fun getCurrentTimeZone(): String {
    return TimeZone.currentSystemDefault().id
}


val timeZones = listOf(
    FavouriteTimeZone(id = "Asia/Karachi", name = "Karachi/Pakistan"),
    FavouriteTimeZone(id = "Asia/Karachi", name = "Lahore/Pakistan"),
    FavouriteTimeZone(id = "Asia/Karachi", name = "Islamabad/Pakistan"),
    FavouriteTimeZone(id = "Asia/Karachi", name = "Faisalabad/Pakistan"),
    FavouriteTimeZone(id = "Asia/Karachi", name = "Rawalpindi/Pakistan"),
    FavouriteTimeZone(id = "Asia/Karachi", name = "Multan/Pakistan"),
    FavouriteTimeZone(id = "Asia/Karachi", name = "Gujranwala/Pakistan"),
    FavouriteTimeZone(id = "Asia/Karachi", name = "Peshawar/Pakistan"),
    FavouriteTimeZone(id = "Asia/Karachi", name = "Quetta/Pakistan"),
    FavouriteTimeZone(id = "Asia/Karachi", name = "Hyderabad/Pakistan"),
    FavouriteTimeZone(id = "Asia/Karachi", name = "Sialkot/Pakistan"),
    FavouriteTimeZone(id = "Asia/Kolkata", name = "Ahmedabad/India"),
    FavouriteTimeZone(id = "Asia/Kolkata", name = "Bengaluru/India"),
    FavouriteTimeZone(id = "Asia/Kolkata", name = "Bhopal/India"),
    FavouriteTimeZone(id = "Asia/Kolkata", name = "Chandigarh/India"),
    FavouriteTimeZone(id = "Asia/Kolkata", name = "Chennai/India"),
    FavouriteTimeZone(id = "Asia/Kolkata", name = "Delhi/India"),
    FavouriteTimeZone(id = "Asia/Kolkata", name = "Hyderabad/India"),
    FavouriteTimeZone(id = "Asia/Kolkata", name = "Jaipur/India"),
    FavouriteTimeZone(id = "Asia/Kolkata", name = "Kolkata/India"),
    FavouriteTimeZone(id = "Asia/Kolkata", name = "Lucknow/India"),
    FavouriteTimeZone(id = "Asia/Kolkata", name = "Mumbai/India"),
    FavouriteTimeZone(id = "Asia/Kolkata", name = "Nagpur/India"),
    FavouriteTimeZone(id = "Asia/Kolkata", name = "Patna/India"),
    FavouriteTimeZone(id = "Asia/Kolkata", name = "Pune/India"),
    FavouriteTimeZone(id = "Asia/Kolkata", name = "Surat/India"),
    FavouriteTimeZone(id = "America/New_York", name = "New York/United States"),
    FavouriteTimeZone(id = "America/New_York", name = "Boston/United States"),
    FavouriteTimeZone(id = "America/New_York", name = "Washington DC/United States"),
    FavouriteTimeZone(id = "America/New_York", name = "Philadelphia/United States"),
    FavouriteTimeZone(id = "America/New_York", name = "Atlanta/United States"),
    FavouriteTimeZone(id = "America/New_York", name = "Miami/United States"),
    FavouriteTimeZone(id = "America/New_York", name = "Detroit/United States"),
    FavouriteTimeZone(id = "America/Chicago", name = "Chicago/United States"),
    FavouriteTimeZone(id = "America/Chicago", name = "Houston/United States"),
    FavouriteTimeZone(id = "America/Chicago", name = "Dallas/United States"),
    FavouriteTimeZone(id = "America/Chicago", name = "New Orleans/United States"),
    FavouriteTimeZone(id = "America/Chicago", name = "Minneapolis/United States"),
    FavouriteTimeZone(id = "America/Denver", name = "Denver/United States"),
    FavouriteTimeZone(id = "America/Denver", name = "Salt Lake City/United States"),
    FavouriteTimeZone(id = "America/Denver", name = "Phoenix/United States"),
    FavouriteTimeZone(id = "America/Los_Angeles", name = "Los Angeles/United States"),
    FavouriteTimeZone(id = "America/Los_Angeles", name = "San Francisco/United States"),
    FavouriteTimeZone(id = "America/Los_Angeles", name = "Seattle/United States"),
    FavouriteTimeZone(id = "America/Los_Angeles", name = "San Diego/United States"),
    FavouriteTimeZone(id = "America/Los_Angeles", name = "Portland/United States"),
    FavouriteTimeZone(id = "America/Anchorage", name = "Anchorage/United States"),
    FavouriteTimeZone(id = "America/Anchorage", name = "Juneau/United States"),
    FavouriteTimeZone(id = "America/Adak", name = "Adak/United States"),
    FavouriteTimeZone(id = "Pacific/Honolulu", name = "Honolulu/United States"),
    FavouriteTimeZone(id = "Asia/Shanghai", name = "Beijing/China"),
    FavouriteTimeZone(id = "Asia/Shanghai", name = "Shanghai/China"),
    FavouriteTimeZone(id = "Asia/Shanghai", name = "Guangzhou/China"),
    FavouriteTimeZone(id = "Asia/Shanghai", name = "Shenzhen/China"),
    FavouriteTimeZone(id = "Asia/Shanghai", name = "Chengdu/China"),
    FavouriteTimeZone(id = "Asia/Shanghai", name = "Chongqing/China"),
    FavouriteTimeZone(id = "Asia/Shanghai", name = "Hangzhou/China"),
    FavouriteTimeZone(id = "Asia/Shanghai", name = "Tianjin/China"),
    FavouriteTimeZone(id = "Asia/Shanghai", name = "Wuhan/China"),
    FavouriteTimeZone(id = "Asia/Shanghai", name = "Xi'an/China"),
    FavouriteTimeZone(id = "Asia/Urumqi", name = "Ürümqi/China"),
    FavouriteTimeZone(id = "Europe/Moscow", name = "Moscow/Russia"),
    FavouriteTimeZone(id = "Europe/Moscow", name = "Saint Petersburg/Russia"),
    FavouriteTimeZone(id = "Europe/Kaliningrad", name = "Kaliningrad/Russia"),
    FavouriteTimeZone(id = "Europe/Volgograd", name = "Volgograd/Russia"),
    FavouriteTimeZone(id = "Europe/Samara", name = "Samara/Russia"),
    FavouriteTimeZone(id = "Asia/Yekaterinburg", name = "Yekaterinburg/Russia"),
    FavouriteTimeZone(id = "Asia/Omsk", name = "Omsk/Russia"),
    FavouriteTimeZone(id = "Asia/Krasnoyarsk", name = "Krasnoyarsk/Russia"),
    FavouriteTimeZone(id = "Asia/Irkutsk", name = "Irkutsk/Russia"),
    FavouriteTimeZone(id = "Asia/Yakutsk", name = "Yakutsk/Russia"),
    FavouriteTimeZone(id = "Asia/Vladivostok", name = "Vladivostok/Russia"),
    FavouriteTimeZone(id = "Asia/Magadan", name = "Magadan/Russia"),
    FavouriteTimeZone(id = "Asia/Kamchatka", name = "Petropavlovsk-Kamchatsky/Russia"),
    FavouriteTimeZone(id = "Australia/Sydney", name = "Sydney/Australia"),
    FavouriteTimeZone(id = "Australia/Sydney", name = "Melbourne/Australia"),
    FavouriteTimeZone(id = "Australia/Sydney", name = "Canberra/Australia"),
    FavouriteTimeZone(id = "Australia/Brisbane", name = "Brisbane/Australia"),
    FavouriteTimeZone(id = "Australia/Adelaide", name = "Adelaide/Australia"),
    FavouriteTimeZone(id = "Australia/Perth", name = "Perth/Australia"),
    FavouriteTimeZone(id = "Australia/Darwin", name = "Darwin/Australia"),
    FavouriteTimeZone(id = "Australia/Hobart", name = "Hobart/Australia"),
    FavouriteTimeZone(id = "America/Sao_Paulo", name = "São Paulo/Brazil"),
    FavouriteTimeZone(id = "America/Sao_Paulo", name = "Rio de Janeiro/Brazil"),
    FavouriteTimeZone(id = "America/Sao_Paulo", name = "Brasília/Brazil"),
    FavouriteTimeZone(id = "America/Manaus", name = "Manaus/Brazil"),
    FavouriteTimeZone(id = "America/Recife", name = "Recife/Brazil"),
    FavouriteTimeZone(id = "America/Noronha", name = "Fernando de Noronha/Brazil"),
    FavouriteTimeZone(id = "America/Toronto", name = "Toronto/Canada"),
    FavouriteTimeZone(id = "America/Toronto", name = "Ottawa/Canada"),
    FavouriteTimeZone(id = "America/Montreal", name = "Montréal/Canada"),
    FavouriteTimeZone(id = "America/Vancouver", name = "Vancouver/Canada"),
    FavouriteTimeZone(id = "America/Winnipeg", name = "Winnipeg/Canada"),
    FavouriteTimeZone(id = "America/Edmonton", name = "Edmonton/Canada"),
    FavouriteTimeZone(id = "America/Halifax", name = "Halifax/Canada"),
    FavouriteTimeZone(id = "America/St_Johns", name = "St. John's/Canada"),
    FavouriteTimeZone(id = "Asia/Jakarta", name = "Jakarta/Indonesia"),
    FavouriteTimeZone(id = "Asia/Jakarta", name = "Surabaya/Indonesia"),
    FavouriteTimeZone(id = "Asia/Makassar", name = "Makassar/Indonesia"),
    FavouriteTimeZone(id = "Asia/Jayapura", name = "Jayapura/Indonesia"),
    FavouriteTimeZone(id = "Asia/Dhaka", name = "Dhaka/Bangladesh"),
    FavouriteTimeZone(id = "Asia/Dhaka", name = "Chittagong/Bangladesh"),
    FavouriteTimeZone(id = "Asia/Tokyo", name = "Tokyo/Japan"),
    FavouriteTimeZone(id = "Asia/Tokyo", name = "Osaka/Japan"),
    FavouriteTimeZone(id = "Asia/Tokyo", name = "Sapporo/Japan"),
    FavouriteTimeZone(id = "Asia/Tokyo", name = "Nagoya/Japan"),
    FavouriteTimeZone(id = "Asia/Seoul", name = "Seoul/South Korea"),
    FavouriteTimeZone(id = "Asia/Seoul", name = "Busan/South Korea"),
    FavouriteTimeZone(id = "Asia/Seoul", name = "Incheon/South Korea"),
    FavouriteTimeZone(id = "Europe/London", name = "London/United Kingdom"),
    FavouriteTimeZone(id = "Europe/London", name = "Manchester/United Kingdom"),
    FavouriteTimeZone(id = "Europe/London", name = "Edinburgh/United Kingdom"),
    FavouriteTimeZone(id = "Europe/London", name = "Birmingham/United Kingdom"),
    FavouriteTimeZone(id = "Europe/Berlin", name = "Berlin/Germany"),
    FavouriteTimeZone(id = "Europe/Berlin", name = "Munich/Germany"),
    FavouriteTimeZone(id = "Europe/Berlin", name = "Frankfurt/Germany"),
    FavouriteTimeZone(id = "Europe/Berlin", name = "Hamburg/Germany"),
    FavouriteTimeZone(id = "Europe/Paris", name = "Paris/France"),
    FavouriteTimeZone(id = "Europe/Paris", name = "Marseille/France"),
    FavouriteTimeZone(id = "Europe/Paris", name = "Lyon/France"),
    FavouriteTimeZone(id = "Asia/Riyadh", name = "Riyadh/Saudi Arabia"),
    FavouriteTimeZone(id = "Asia/Riyadh", name = "Jeddah/Saudi Arabia"),
    FavouriteTimeZone(id = "Asia/Riyadh", name = "Mecca/Saudi Arabia"),
    FavouriteTimeZone(id = "Asia/Dubai", name = "Dubai/United Arab Emirates"),
    FavouriteTimeZone(id = "Asia/Dubai", name = "Abu Dhabi/United Arab Emirates"),
    FavouriteTimeZone(id = "Africa/Cairo", name = "Cairo/Egypt"),
    FavouriteTimeZone(id = "Africa/Cairo", name = "Alexandria/Egypt"),
    FavouriteTimeZone(id = "Africa/Johannesburg", name = "Johannesburg/South Africa"),
    FavouriteTimeZone(id = "Africa/Johannesburg", name = "Cape Town/South Africa"),
    FavouriteTimeZone(id = "Africa/Johannesburg", name = "Durban/South Africa"),
    FavouriteTimeZone(id = "Africa/Lagos", name = "Lagos/Nigeria"),
    FavouriteTimeZone(id = "Africa/Lagos", name = "Abuja/Nigeria"),
    FavouriteTimeZone(id = "Africa/Nairobi", name = "Nairobi/Kenya"),
    FavouriteTimeZone(id = "Africa/Nairobi", name = "Mombasa/Kenya"),
    FavouriteTimeZone(id = "Asia/Singapore", name = "Singapore"),
    FavouriteTimeZone(id = "Asia/Kuala_Lumpur", name = "Kuala Lumpur/Malaysia"),
    FavouriteTimeZone(id = "Asia/Kuala_Lumpur", name = "George Town/Malaysia"),
    FavouriteTimeZone(id = "Asia/Bangkok", name = "Bangkok/Thailand"),
    FavouriteTimeZone(id = "Asia/Bangkok", name = "Chiang Mai/Thailand"),
    FavouriteTimeZone(id = "Asia/Ho_Chi_Minh", name = "Ho Chi Minh City/Vietnam"),
    FavouriteTimeZone(id = "Asia/Ho_Chi_Minh", name = "Hanoi/Vietnam"),
    FavouriteTimeZone(id = "Asia/Manila", name = "Manila/Philippines"),
    FavouriteTimeZone(id = "Asia/Manila", name = "Davao/Philippines"),
    FavouriteTimeZone(id = "Asia/Manila", name = "Cebu/Philippines"),
    FavouriteTimeZone(id = "America/Argentina/Buenos_Aires", name = "Buenos Aires/Argentina"),
    FavouriteTimeZone(id = "America/Argentina/Buenos_Aires", name = "Córdoba/Argentina"),
    FavouriteTimeZone(id = "America/Argentina/Buenos_Aires", name = "Rosario/Argentina"),
    FavouriteTimeZone(id = "America/Mexico_City", name = "Mexico City/Mexico"),
    FavouriteTimeZone(id = "America/Mexico_City", name = "Guadalajara/Mexico"),
    FavouriteTimeZone(id = "America/Tijuana", name = "Tijuana/Mexico"),
    FavouriteTimeZone(id = "America/Cancun", name = "Cancún/Mexico"),
    FavouriteTimeZone(id = "Europe/Istanbul", name = "Istanbul/Turkey"),
    FavouriteTimeZone(id = "Europe/Istanbul", name = "Ankara/Turkey"),
    FavouriteTimeZone(id = "Europe/Istanbul", name = "Izmir/Turkey"),
    FavouriteTimeZone(id = "Europe/Kyiv", name = "Kyiv/Ukraine"),
    FavouriteTimeZone(id = "Europe/Kyiv", name = "Kharkiv/Ukraine"),
    FavouriteTimeZone(id = "Europe/Kyiv", name = "Odesa/Ukraine"),
    FavouriteTimeZone(id = "Europe/Rome", name = "Rome/Italy"),
    FavouriteTimeZone(id = "Europe/Rome", name = "Milan/Italy"),
    FavouriteTimeZone(id = "Europe/Rome", name = "Naples/Italy"),
    FavouriteTimeZone(id = "Europe/Madrid", name = "Madrid/Spain"),
    FavouriteTimeZone(id = "Europe/Madrid", name = "Barcelona/Spain"),
    FavouriteTimeZone(id = "Europe/Madrid", name = "Valencia/Spain"),
    FavouriteTimeZone(id = "Atlantic/Canary", name = "Tenerife/Spain"),
    FavouriteTimeZone(id = "Europe/Amsterdam", name = "Amsterdam/Netherlands"),
    FavouriteTimeZone(id = "Europe/Amsterdam", name = "Rotterdam/Netherlands"),
    FavouriteTimeZone(id = "Europe/Zurich", name = "Zurich/Switzerland"),
    FavouriteTimeZone(id = "Europe/Zurich", name = "Geneva/Switzerland"),
    FavouriteTimeZone(id = "Europe/Stockholm", name = "Stockholm/Sweden"),
    FavouriteTimeZone(id = "Europe/Stockholm", name = "Gothenburg/Sweden"),
    FavouriteTimeZone(id = "Europe/Oslo", name = "Oslo/Norway"),
    FavouriteTimeZone(id = "Europe/Oslo", name = "Bergen/Norway"),
    FavouriteTimeZone(id = "Pacific/Auckland", name = "Auckland/New Zealand"),
    FavouriteTimeZone(id = "Pacific/Auckland", name = "Wellington/New Zealand"),
    FavouriteTimeZone(id = "Pacific/Chatham", name = "Chatham Islands/New Zealand"),
    FavouriteTimeZone(id = "Pacific/Kiritimati", name = "Kiritimati/Kiribati"),
    FavouriteTimeZone(id = "Asia/Kabul", name = "Kabul/Afghanistan"),
    FavouriteTimeZone(id = "Europe/Tirane", name = "Tirane/Albania"),
    FavouriteTimeZone(id = "Africa/Algiers", name = "Algiers/Algeria"),
    FavouriteTimeZone(id = "Europe/Andorra", name = "Andorra la Vella/Andorra"),
    FavouriteTimeZone(id = "Africa/Luanda", name = "Luanda/Angola"),
    FavouriteTimeZone(id = "Asia/Yerevan", name = "Yerevan/Armenia"),
    FavouriteTimeZone(id = "Europe/Vienna", name = "Vienna/Austria"),
    FavouriteTimeZone(id = "Asia/Baku", name = "Baku/Azerbaijan"),
    FavouriteTimeZone(id = "America/Nassau", name = "Nassau/Bahamas"),
    FavouriteTimeZone(id = "Asia/Bahrain", name = "Manama/Bahrain"),
    FavouriteTimeZone(id = "Europe/Minsk", name = "Minsk/Belarus"),
    FavouriteTimeZone(id = "Europe/Brussels", name = "Brussels/Belgium"),
    FavouriteTimeZone(id = "America/La_Paz", name = "La Paz/Bolivia"),
    FavouriteTimeZone(id = "Europe/Sarajevo", name = "Sarajevo/Bosnia & Herzegovina"),
    FavouriteTimeZone(id = "Africa/Gaborone", name = "Gaborone/Botswana"),
    FavouriteTimeZone(id = "Asia/Brunei", name = "Bandar Seri Begawan/Brunei"),
    FavouriteTimeZone(id = "Europe/Sofia", name = "Sofia/Bulgaria"),
    FavouriteTimeZone(id = "Asia/Phnom_Penh", name = "Phnom Penh/Cambodia"),
    FavouriteTimeZone(id = "Africa/Douala", name = "Douala/Cameroon"),
    FavouriteTimeZone(id = "America/Santiago", name = "Santiago/Chile"),
    FavouriteTimeZone(id = "Pacific/Easter", name = "Easter Island/Chile"),
    FavouriteTimeZone(id = "America/Bogota", name = "Bogotá/Colombia"),
    FavouriteTimeZone(id = "America/Costa_Rica", name = "San José/Costa Rica"),
    FavouriteTimeZone(id = "Europe/Zagreb", name = "Zagreb/Croatia"),
    FavouriteTimeZone(id = "America/Havana", name = "Havana/Cuba"),
    FavouriteTimeZone(id = "Asia/Nicosia", name = "Nicosia/Cyprus"),
    FavouriteTimeZone(id = "Asia/Famagusta", name = "North Nicosia/Cyprus"),
    FavouriteTimeZone(id = "Europe/Prague", name = "Prague/Czechia"),
    FavouriteTimeZone(id = "Europe/Copenhagen", name = "Copenhagen/Denmark"),
    FavouriteTimeZone(id = "America/Santo_Domingo", name = "Santo Domingo/Dominican Republic"),
    FavouriteTimeZone(id = "America/Guayaquil", name = "Quito/Ecuador"),
    FavouriteTimeZone(id = "Pacific/Galapagos", name = "Galapagos/Ecuador"),
    FavouriteTimeZone(id = "America/El_Salvador", name = "San Salvador/El Salvador"),
    FavouriteTimeZone(id = "Europe/Tallinn", name = "Tallinn/Estonia"),
    FavouriteTimeZone(id = "Africa/Addis_Ababa", name = "Addis Ababa/Ethiopia"),
    FavouriteTimeZone(id = "Pacific/Fiji", name = "Suva/Fiji"),
    FavouriteTimeZone(id = "Europe/Helsinki", name = "Helsinki/Finland"),
    FavouriteTimeZone(id = "Asia/Tbilisi", name = "Tbilisi/Georgia"),
    FavouriteTimeZone(id = "Africa/Accra", name = "Accra/Ghana"),
    FavouriteTimeZone(id = "Europe/Athens", name = "Athens/Greece"),
    FavouriteTimeZone(id = "America/Guatemala", name = "Guatemala City/Guatemala"),
    FavouriteTimeZone(id = "America/Tegucigalpa", name = "Tegucigalpa/Honduras"),
    FavouriteTimeZone(id = "Europe/Budapest", name = "Budapest/Hungary"),
    FavouriteTimeZone(id = "Atlantic/Reykjavik", name = "Reykjavík/Iceland"),
    FavouriteTimeZone(id = "Asia/Tehran", name = "Tehran/Iran"),
    FavouriteTimeZone(id = "Asia/Baghdad", name = "Baghdad/Iraq"),
    FavouriteTimeZone(id = "Europe/Dublin", name = "Dublin/Ireland"),
    FavouriteTimeZone(id = "Asia/Jerusalem", name = "Jerusalem/Israel"),
    FavouriteTimeZone(id = "Asia/Gaza", name = "Gaza/Palestine"),
    FavouriteTimeZone(id = "Asia/Hebron", name = "Hebron/Palestine"),
    FavouriteTimeZone(id = "Africa/Abidjan", name = "Abidjan/Ivory Coast"),
    FavouriteTimeZone(id = "America/Jamaica", name = "Kingston/Jamaica"),
    FavouriteTimeZone(id = "Asia/Amman", name = "Amman/Jordan"),
    FavouriteTimeZone(id = "Asia/Almaty", name = "Almaty/Kazakhstan"),
    FavouriteTimeZone(id = "Asia/Qostanay", name = "Astana/Kazakhstan"),
    FavouriteTimeZone(id = "Asia/Kuwait", name = "Kuwait City/Kuwait"),
    FavouriteTimeZone(id = "Europe/Riga", name = "Riga/Latvia"),
    FavouriteTimeZone(id = "Asia/Beirut", name = "Beirut/Lebanon"),
    FavouriteTimeZone(id = "Africa/Tripoli", name = "Tripoli/Libya"),
    FavouriteTimeZone(id = "Europe/Vaduz", name = "Vaduz/Liechtenstein"),
    FavouriteTimeZone(id = "Europe/Vilnius", name = "Vilnius/Lithuania"),
    FavouriteTimeZone(id = "Europe/Luxembourg", name = "Luxembourg"),
    FavouriteTimeZone(id = "Europe/Skopje", name = "Skopje/North Macedonia"),
    FavouriteTimeZone(id = "Indian/Antananarivo", name = "Antananarivo/Madagascar"),
    FavouriteTimeZone(id = "Indian/Maldives", name = "Malé/Maldives"),
    FavouriteTimeZone(id = "Europe/Malta", name = "Valletta/Malta"),
    FavouriteTimeZone(id = "Indian/Mauritius", name = "Port Louis/Mauritius"),
    FavouriteTimeZone(id = "Europe/Chisinau", name = "Chișinău/Moldova"),
    FavouriteTimeZone(id = "Europe/Monaco", name = "Monaco"),
    FavouriteTimeZone(id = "Asia/Ulaanbaatar", name = "Ulaanbaatar/Mongolia"),
    FavouriteTimeZone(id = "Europe/Podgorica", name = "Podgorica/Montenegro"),
    FavouriteTimeZone(id = "Africa/Casablanca", name = "Casablanca/Morocco"),
    FavouriteTimeZone(id = "Asia/Yangon", name = "Yangon/Myanmar"),
    FavouriteTimeZone(id = "Asia/Kathmandu", name = "Kathmandu/Nepal"),
    FavouriteTimeZone(id = "Asia/Pyongyang", name = "Pyongyang/North Korea"),
    FavouriteTimeZone(id = "Asia/Muscat", name = "Muscat/Oman"),
    FavouriteTimeZone(id = "America/Panama", name = "Panama City/Panama"),
    FavouriteTimeZone(id = "America/Asuncion", name = "Asunción/Paraguay"),
    FavouriteTimeZone(id = "America/Lima", name = "Lima/Peru"),
    FavouriteTimeZone(id = "Europe/Warsaw", name = "Warsaw/Poland"),
    FavouriteTimeZone(id = "Europe/Lisbon", name = "Lisbon/Portugal"),
    FavouriteTimeZone(id = "Atlantic/Azores", name = "Ponta Delgada/Portugal"),
    FavouriteTimeZone(id = "Atlantic/Madeira", name = "Funchal/Portugal"),
    FavouriteTimeZone(id = "Asia/Qatar", name = "Doha/Qatar"),
    FavouriteTimeZone(id = "Europe/Bucharest", name = "Bucharest/Romania"),
    FavouriteTimeZone(id = "Africa/Kigali", name = "Kigali/Rwanda"),
    FavouriteTimeZone(id = "Africa/Dakar", name = "Dakar/Senegal"),
    FavouriteTimeZone(id = "Europe/Belgrade", name = "Belgrade/Serbia"),
    FavouriteTimeZone(id = "Indian/Mahe", name = "Victoria/Seychelles"),
    FavouriteTimeZone(id = "Africa/Freetown", name = "Freetown/Sierra Leone"),
    FavouriteTimeZone(id = "Europe/Bratislava", name = "Bratislava/Slovakia"),
    FavouriteTimeZone(id = "Europe/Ljubljana", name = "Ljubljana/Slovenia"),
    FavouriteTimeZone(id = "Africa/Mogadishu", name = "Mogadishu/Somalia"),
    FavouriteTimeZone(id = "Asia/Colombo", name = "Colombo/Sri Lanka"),
    FavouriteTimeZone(id = "Africa/Khartoum", name = "Khartoum/Sudan"),
    FavouriteTimeZone(id = "Asia/Damascus", name = "Damascus/Syria"),
    FavouriteTimeZone(id = "Asia/Taipei", name = "Taipei/Taiwan"),
    FavouriteTimeZone(id = "Asia/Dushanbe", name = "Dushanbe/Tajikistan"),
    FavouriteTimeZone(id = "Africa/Dar_es_Salaam", name = "Dar es Salaam/Tanzania"),
    FavouriteTimeZone(id = "Asia/Dili", name = "Dili/Timor-Leste"),
    FavouriteTimeZone(id = "Africa/Tunis", name = "Tunis/Tunisia"),
    FavouriteTimeZone(id = "Asia/Ashgabat", name = "Ashgabat/Turkmenistan"),
    FavouriteTimeZone(id = "Africa/Kampala", name = "Kampala/Uganda"),
    FavouriteTimeZone(id = "America/Montevideo", name = "Montevideo/Uruguay"),
    FavouriteTimeZone(id = "Asia/Tashkent", name = "Tashkent/Uzbekistan"),
    FavouriteTimeZone(id = "Asia/Samarkand", name = "Samarkand/Uzbekistan"),
    FavouriteTimeZone(id = "Europe/Vatican", name = "Vatican City"),
    FavouriteTimeZone(id = "America/Caracas", name = "Caracas/Venezuela"),
    FavouriteTimeZone(id = "Asia/Aden", name = "Sana'a/Yemen"),
    FavouriteTimeZone(id = "Africa/Lusaka", name = "Lusaka/Zambia"),
    FavouriteTimeZone(id = "Africa/Harare", name = "Harare/Zimbabwe"),
    FavouriteTimeZone(id = "UTC", name = "Coordinated Universal Time/UTC"),
    FavouriteTimeZone(id = "UTC", name = "GMT")
    // Africa
//    "Africa/Abidjan",
//    "Africa/Accra",
//    "Africa/Addis_Ababa",
//    "Africa/Algiers",
//    "Africa/Asmara",
//    "Africa/Bamako",
//    "Africa/Bangui",
//    "Africa/Banjul",
//    "Africa/Bissau",
//    "Africa/Blantyre",
//    "Africa/Brazzaville",
//    "Africa/Bujumbura",
//    "Africa/Cairo",
//    "Africa/Casablanca",
//    "Africa/Ceuta",
//    "Africa/Conakry",
//    "Africa/Dakar",
//    "Africa/Dar_es_Salaam",
//    "Africa/Djibouti",
//    "Africa/Douala",
//    "Africa/El_Aaiun",
//    "Africa/Freetown",
//    "Africa/Gaborone",
//    "Africa/Harare",
//    "Africa/Johannesburg",
//    "Africa/Juba",
//    "Africa/Kampala",
//    "Africa/Khartoum",
//    "Africa/Kigali",
//    "Africa/Kinshasa",
//    "Africa/Lagos",
//    "Africa/Libreville",
//    "Africa/Lome",
//    "Africa/Luanda",
//    "Africa/Lubumbashi",
//    "Africa/Lusaka",
//    "Africa/Malabo",
//    "Africa/Maputo",
//    "Africa/Maseru",
//    "Africa/Mbabane",
//    "Africa/Mogadishu",
//    "Africa/Monrovia",
//    "Africa/Nairobi",
//    "Africa/Ndjamena",
//    "Africa/Niamey",
//    "Africa/Nouakchott",
//    "Africa/Ouagadougou",
//    "Africa/Porto-Novo",
//    "Africa/Sao_Tome",
//    "Africa/Tripoli",
//    "Africa/Tunis",
//    "Africa/Windhoek",
//
//    // America
//    "America/Adak",
//    "America/Anchorage",
//    "America/Anguilla",
//    "America/Antigua",
//    "America/Araguaina",
//    "America/Argentina/Buenos_Aires",
//    "America/Argentina/Catamarca",
//    "America/Argentina/Cordoba",
//    "America/Argentina/Jujuy",
//    "America/Argentina/La_Rioja",
//    "America/Argentina/Mendoza",
//    "America/Argentina/Rio_Gallegos",
//    "America/Argentina/Salta",
//    "America/Argentina/San_Juan",
//    "America/Argentina/San_Luis",
//    "America/Argentina/Tucuman",
//    "America/Argentina/Ushuaia",
//    "America/Aruba",
//    "America/Asuncion",
//    "America/Atikokan",
//    "America/Bahia",
//    "America/Bahia_Banderas",
//    "America/Barbados",
//    "America/Belem",
//    "America/Belize",
//    "America/Blanc-Sablon",
//    "America/Boa_Vista",
//    "America/Bogota",
//    "America/Boise",
//    "America/Cambridge_Bay",
//    "America/Campo_Grande",
//    "America/Cancun",
//    "America/Caracas",
//    "America/Cayenne",
//    "America/Cayman",
//    "America/Chicago",
//    "America/Chihuahua",
//    "America/Ciudad_Juarez",
//    "America/Costa_Rica",
//    "America/Creston",
//    "America/Cuiaba",
//    "America/Curacao",
//    "America/Danmarkshavn",
//    "America/Dawson",
//    "America/Dawson_Creek",
//    "America/Denver",
//    "America/Detroit",
//    "America/Dominica",
//    "America/Edmonton",
//    "America/Eirunepe",
//    "America/El_Salvador",
//    "America/Fort_Nelson",
//    "America/Fortaleza",
//    "America/Glace_Bay",
//    "America/Goose_Bay",
//    "America/Grand_Turk",
//    "America/Grenada",
//    "America/Guadeloupe",
//    "America/Guatemala",
//    "America/Guayaquil",
//    "America/Guyana",
//    "America/Halifax",
//    "America/Havana",
//    "America/Hermosillo",
//    "America/Indiana/Indianapolis",
//    "America/Indiana/Knox",
//    "America/Indiana/Marengo",
//    "America/Indiana/Petersburg",
//    "America/Indiana/Tell_City",
//    "America/Indiana/Vevay",
//    "America/Indiana/Vincennes",
//    "America/Indiana/Winamac",
//    "America/Inuvik",
//    "America/Iqaluit",
//    "America/Jamaica",
//    "America/Juneau",
//    "America/Kentucky/Louisville",
//    "America/Kentucky/Monticello",
//    "America/Kralendijk",
//    "America/La_Paz",
//    "America/Lima",
//    "America/Los_Angeles",
//    "America/Lower_Princes",
//    "America/Maceio",
//    "America/Managua",
//    "America/Manaus",
//    "America/Marigot",
//    "America/Martinique",
//    "America/Matamoros",
//    "America/Mazatlan",
//    "America/Menominee",
//    "America/Merida",
//    "America/Metlakatla",
//    "America/Mexico_City",
//    "America/Miquelon",
//    "America/Moncton",
//    "America/Monterrey",
//    "America/Montevideo",
//    "America/Montserrat",
//    "America/Nassau",
//    "America/New_York",
//    "America/Nome",
//    "America/Noronha",
//    "America/North_Dakota/Beulah",
//    "America/North_Dakota/Center",
//    "America/North_Dakota/New_Salem",
//    "America/Nuuk",
//    "America/Ojinaga",
//    "America/Panama",
//    "America/Paramaribo",
//    "America/Phoenix",
//    "America/Port-au-Prince",
//    "America/Port_of_Spain",
//    "America/Porto_Velho",
//    "America/Puerto_Rico",
//    "America/Punta_Arenas",
//    "America/Rankin_Inlet",
//    "America/Recife",
//    "America/Regina",
//    "America/Resolute",
//    "America/Rio_Branco",
//    "America/Santarem",
//    "America/Santiago",
//    "America/Santo_Domingo",
//    "America/Sao_Paulo",
//    "America/Scoresbysund",
//    "America/Sitka",
//    "America/St_Barthelemy",
//    "America/St_Johns",
//    "America/St_Kitts",
//    "America/St_Lucia",
//    "America/St_Thomas",
//    "America/St_Vincent",
//    "America/Swift_Current",
//    "America/Tegucigalpa",
//    "America/Thule",
//    "America/Tijuana",
//    "America/Toronto",
//    "America/Tortola",
//    "America/Vancouver",
//    "America/Whitehorse",
//    "America/Winnipeg",
//    "America/Yakutat",
//
//    // Antarctica
//    "Antarctica/Casey",
//    "Antarctica/Davis",
//    "Antarctica/DumontDUrville",
//    "Antarctica/Macquarie",
//    "Antarctica/Mawson",
//    "Antarctica/McMurdo",
//    "Antarctica/Palmer",
//    "Antarctica/Rothera",
//    "Antarctica/Syowa",
//    "Antarctica/Troll",
//    "Antarctica/Vostok",
//
//    // Arctic
//    "Arctic/Longyearbyen",
//
//    // Asia
//    "Asia/Aden",
//    "Asia/Almaty",
//    "Asia/Amman",
//    "Asia/Anadyr",
//    "Asia/Aqtau",
//    "Asia/Aqtobe",
//    "Asia/Ashgabat",
//    "Asia/Atyrau",
//    "Asia/Baghdad",
//    "Asia/Bahrain",
//    "Asia/Baku",
//    "Asia/Bangkok",
//    "Asia/Barnaul",
//    "Asia/Beirut",
//    "Asia/Bishkek",
//    "Asia/Brunei",
//    "Asia/Chita",
//    "Asia/Choibalsan",
//    "Asia/Colombo",
//    "Asia/Damascus",
//    "Asia/Dhaka",
//    "Asia/Dili",
//    "Asia/Dubai",
//    "Asia/Dushanbe",
//    "Asia/Famagusta",
//    "Asia/Gaza",
//    "Asia/Hebron",
//    "Asia/Ho_Chi_Minh",
//    "Asia/Hong_Kong",
//    "Asia/Hovd",
//    "Asia/Irkutsk",
//    "Asia/Jakarta",
//    "Asia/Jayapura",
//    "Asia/Jerusalem",
//    "Asia/Kabul",
//    "Asia/Kamchatka",
//    "Asia/Karachi",
//    "Asia/Kathmandu",
//    "Asia/Khandyga",
//    "Asia/Kolkata",
//    "Asia/Krasnoyarsk",
//    "Asia/Kuala_Lumpur",
//    "Asia/Kuching",
//    "Asia/Kuwait",
//    "Asia/Macau",
//    "Asia/Magadan",
//    "Asia/Makassar",
//    "Asia/Manila",
//    "Asia/Muscat",
//    "Asia/Nicosia",
//    "Asia/Novokuznetsk",
//    "Asia/Novosibirsk",
//    "Asia/Omsk",
//    "Asia/Oral",
//    "Asia/Phnom_Penh",
//    "Asia/Pontianak",
//    "Asia/Pyongyang",
//    "Asia/Qatar",
//    "Asia/Qostanay",
//    "Asia/Qyzylorda",
//    "Asia/Riyadh",
//    "Asia/Sakhalin",
//    "Asia/Samarkand",
//    "Asia/Seoul",
//    "Asia/Shanghai",
//    "Asia/Singapore",
//    "Asia/Srednekolymsk",
//    "Asia/Taipei",
//    "Asia/Tashkent",
//    "Asia/Tbilisi",
//    "Asia/Tehran",
//    "Asia/Thimphu",
//    "Asia/Tokyo",
//    "Asia/Tomsk",
//    "Asia/Ulaanbaatar",
//    "Asia/Urumqi",
//    "Asia/Ust-Nera",
//    "Asia/Vientiane",
//    "Asia/Vladivostok",
//    "Asia/Yakutsk",
//    "Asia/Yangon",
//    "Asia/Yekaterinburg",
//    "Asia/Yerevan",
//
//    // Atlantic
//    "Atlantic/Azores",
//    "Atlantic/Bermuda",
//    "Atlantic/Canary",
//    "Atlantic/Cape_Verde",
//    "Atlantic/Faroe",
//    "Atlantic/Madeira",
//    "Atlantic/Reykjavik",
//    "Atlantic/South_Georgia",
//    "Atlantic/St_Helena",
//    "Atlantic/Stanley",
//
//    // Australia
//    "Australia/Adelaide",
//    "Australia/Brisbane",
//    "Australia/Broken_Hill",
//    "Australia/Darwin",
//    "Australia/Eucla",
//    "Australia/Hobart",
//    "Australia/Lindeman",
//    "Australia/Lord_Howe",
//    "Australia/Melbourne",
//    "Australia/Perth",
//    "Australia/Sydney",
//
//    // Europe
//    "Europe/Amsterdam",
//    "Europe/Andorra",
//    "Europe/Astrakhan",
//    "Europe/Athens",
//    "Europe/Belgrade",
//    "Europe/Berlin",
//    "Europe/Bratislava",
//    "Europe/Brussels",
//    "Europe/Bucharest",
//    "Europe/Budapest",
//    "Europe/Busingen",
//    "Europe/Chisinau",
//    "Europe/Copenhagen",
//    "Europe/Dublin",
//    "Europe/Gibraltar",
//    "Europe/Guernsey",
//    "Europe/Helsinki",
//    "Europe/Isle_of_Man",
//    "Europe/Istanbul",
//    "Europe/Jersey",
//    "Europe/Kaliningrad",
//    "Europe/Kirov",
//    "Europe/Kyiv",
//    "Europe/Lisbon",
//    "Europe/Ljubljana",
//    "Europe/London",
//    "Europe/Luxembourg",
//    "Europe/Madrid",
//    "Europe/Malta",
//    "Europe/Mariehamn",
//    "Europe/Minsk",
//    "Europe/Monaco",
//    "Europe/Moscow",
//    "Europe/Oslo",
//    "Europe/Paris",
//    "Europe/Podgorica",
//    "Europe/Prague",
//    "Europe/Riga",
//    "Europe/Rome",
//    "Europe/Samara",
//    "Europe/San_Marino",
//    "Europe/Sarajevo",
//    "Europe/Saratov",
//    "Europe/Simferopol",
//    "Europe/Skopje",
//    "Europe/Sofia",
//    "Europe/Stockholm",
//    "Europe/Tallinn",
//    "Europe/Tirane",
//    "Europe/Ulyanovsk",
//    "Europe/Vaduz",
//    "Europe/Vatican",
//    "Europe/Vienna",
//    "Europe/Vilnius",
//    "Europe/Volgograd",
//    "Europe/Warsaw",
//    "Europe/Zagreb",
//    "Europe/Zurich",
//
//    // Indian
//    "Indian/Antananarivo",
//    "Indian/Chagos",
//    "Indian/Christmas",
//    "Indian/Cocos",
//    "Indian/Comoro",
//    "Indian/Kerguelen",
//    "Indian/Mahe",
//    "Indian/Maldives",
//    "Indian/Mauritius",
//    "Indian/Mayotte",
//    "Indian/Reunion",
//
//    // Pacific
//    "Pacific/Apia",
//    "Pacific/Auckland",
//    "Pacific/Bougainville",
//    "Pacific/Chatham",
//    "Pacific/Chuuk",
//    "Pacific/Easter",
//    "Pacific/Efate",
//    "Pacific/Fakaofo",
//    "Pacific/Fiji",
//    "Pacific/Funafuti",
//    "Pacific/Galapagos",
//    "Pacific/Gambier",
//    "Pacific/Guadalcanal",
//    "Pacific/Guam",
//    "Pacific/Honolulu",
//    "Pacific/Kanton",
//    "Pacific/Kiritimati",
//    "Pacific/Kosrae",
//    "Pacific/Kwajalein",
//    "Pacific/Majuro",
//    "Pacific/Marquesas",
//    "Pacific/Midway",
//    "Pacific/Nauru",
//    "Pacific/Niue",
//    "Pacific/Norfolk",
//    "Pacific/Noumea",
//    "Pacific/Pago_Pago",
//    "Pacific/Palau",
//    "Pacific/Pitcairn",
//    "Pacific/Pohnpei",
//    "Pacific/Port_Moresby",
//    "Pacific/Rarotonga",
//    "Pacific/Saipan",
//    "Pacific/Tahiti",
//    "Pacific/Tarawa",
//    "Pacific/Tongatapu",
//    "Pacific/Wake",
//    "Pacific/Wallis",
//
//    // UTC
//    "UTC"
)


